"""add column operation_type to trades

Revision ID: 6dc61cdd31fa
Revises: d75bffe9328a
Create Date: 2025-05-03 01:29:39.676787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc61cdd31fa'
down_revision: Union[str, None] = 'd75bffe9328a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('operation_type', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'operation_type')
    # ### end Alembic commands ###
