"""add testnet keys

Revision ID: a7278a3a9083
Revises: e801101c4f2a
Create Date: 2025-05-04 20:39:55.616766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7278a3a9083'
down_revision: Union[str, None] = 'e801101c4f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('testnet_api_key', sa.String(length=255), nullable=True))
    op.add_column('user_credentials', sa.Column('testnet_api_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'testnet_api_secret')
    op.drop_column('user_credentials', 'testnet_api_key')
    # ### end Alembic commands ###
