"""initial

Revision ID: d75bffe9328a
Revises: 
Create Date: 2025-05-02 00:20:04.506976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75bffe9328a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cripto_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('crypto_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('cripto_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('on_testnet', sa.Boolean(), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=False),
    sa.Column('quote_qty', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('auto_positions',
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('sell_date', sa.DateTime(), nullable=True),
    sa.Column('sell_trade_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sell_trade_id'], ['trades.order_id'], ),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_table('cripto_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_email', sa.Integer(), nullable=False),
    sa.Column('id_cripto', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Numeric(), nullable=False),
    sa.Column('greater_than_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cripto'], ['cripto_currency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_email'], ['cripto_email.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cripto_threshold')
    op.drop_table('auto_positions')
    op.drop_table('trades')
    op.drop_table('cripto_email')
    op.drop_table('cripto_currency')
    # ### end Alembic commands ###
