"""add user id at auto buy

Revision ID: e475edce7e4e
Revises: a7278a3a9083
Create Date: 2025-05-05 00:17:22.127805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e475edce7e4e'
down_revision: Union[str, None] = 'a7278a3a9083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_buy_quota', sa.Column('crypto_symbol', sa.String(length=10), nullable=False))
    op.add_column('auto_positions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'auto_positions', 'user_credentials', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_purchase_config', 'crypto_symbol',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_purchase_config', 'crypto_symbol',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'auto_positions', type_='foreignkey')
    op.drop_column('auto_positions', 'user_id')
    op.drop_column('auto_buy_quota', 'crypto_symbol')
    # ### end Alembic commands ###
